### ISSUE TITLE
Podcast-cli download files everytime

### ISSUE THREAD

**Issue by Monirzadeh** [goulinkh/podcast-cli#1]
hi
if you download an episode and exit, you should download that episode again in next time.
i think podcast-cli should save file on disk and read that from disk for the next time.

**Comment by goulinkh** [comment]
It's is indeed saved to the disk to the `/tmp` folder. This is a temporary solution until a solve the issue of audio streaming.

**Comment by Monirzadeh** [comment]
for a limit access to the internet it is so important (someone like me)
https://github.com/goulinkh/podcast-cli/issues/3#issuecomment-610493121
it can be optional. anybody can active that in config if he need.
