### ISSUE TITLE
command line arguments: RSS URL, episode offset

### ISSUE THREAD

**Issue by tripper54** [goulinkh/podcast-cli#14]
Hello, 

What an awesome project!

I would really like some command line options so I could start playing an episode from the command line, eg
`pocast-cli --rss https://rss.whooshkaa.com/rss/podcast/id/12924`
This would start playing the latest episode, or you could play an older one using an offset switch, eg
`pocast-cli --rss https://rss.whooshkaa.com/rss/podcast/id/12924 --offset 5`

**Comment by goulinkh** [comment]
Hello @tripper54 ,

I am glad that you like the project. It's interesting, i will added this functionality as soon as possible :)

**Comment by r3k2** [comment]
cool, wont be to hard if you use viper/cobra
