### ISSUE TITLE
Implementing Queue

### ISSUE THREAD

**Issue by keiohtani** [goulinkh/podcast-cli#15]
Thank you for the great app! 

Currently, the app does not support "play next" functionality, but it would be quite useful to have that so that users do not need to select what to play next every time a story ends. 

Thanks.

**Comment by goulinkh** [comment]
Hello @keiohtani ,

Thank you for your feedback, I agree with you it's more convenient to go to the next episode after the current is finished.

Best Regards.

**Comment by keiohtani** [comment]
Thank you! @goulinkh

**Comment by goulinkh** [comment]
You are welcome :)
